# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestFireBase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestFireBase
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'


end
